# configure vscode yaml support https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
# yaml-language-server: $schema=https://fasterci.com/config.schema.json
workflows:
    - name: faster CI
      image: us.gcr.io/fasterci/bazelbuilder:d278ee1
      on:
          push:
              branches:
                  - main
          pull_request:
            branches: ["**"]
      steps:
          - name: bazel test
            bazel:
                build_targets:
                    - //...
                test_targets:
                    - //...
          - name: e2e/link_js_package
            working-directory: e2e/link_js_package
            bazel:
                build_targets:
                    - //...
                test_targets:
                    - //...
          - name: e2e/pnpm_workspace
            working-directory: e2e/pnpm_workspace
            bazel:
                build_targets:
                    - //...
                test_targets:
                    - //...
          - name: e2e/pnpm_workspace_dot_dot
            working-directory: e2e/pnpm_workspace_dot_dot
            bazel:
                build_targets:
                    - //...
                test_targets:
                    - //...
          - name: e2e/rules_foo
            working-directory: e2e/rules_foo
            bazel:
                build_targets:
                    - //...
                test_targets:
                    - //...
